### ISSUE TITLE
awx is not allowed to pull the execution environment

### ISSUE THREAD

**Issue by andysmagana** [tmichett/AnsiblePlaybooks#15]
during a template job in ansible automation job it looks like awx is not allowed to pull the execution environment.  I can sudo su - awx and push and pull the ee-supported-rhel8 but it dies in the Ansible Automation Platform WebUI.

**Comment by tmichett** [comment]
@andysmagana - 

I'm going to need some more information here. Are you referring to one of my examples from the repo, is this in a playbook I created? What is the context here?

**Comment by andysmagana** [comment]
Hello Travis,

I apologize for the lack of information:

Installed with the AAP 4.4.8 bundle as a standalone disconnected to have
its own database I deleted the EE's and setup ansible private hub on a
separate box and have the EE's from the Private Hub to be pulled on jobs.

My issue today is when I run an ad-hoc job against a test box from an
inventory it spits out "Error container create failed ( no logs from conmon
) common bytes "": readObjectStart: expect ....... I have seen some github
issues related to this error but referring to podman, my issue is happening
using the WebUI.

Right now I am thinking somehow awx is not allowed to use any of the
credentials I created including the API Token credentials. I have a
container registry credential of username and password and nothing is
working regarding just a simple playbook ping or command uptime it just
stops when it tries to pull the EE from the private hub.

Someone suggested go into awx and create a auth.json with a username and
password via base64 to get the job done but no love.

**Comment by tmichett** [comment]
Ah - so this issue has nothing to do with me or my repository ...

Most likely the issue is with the container registry credentials and the specific execution environment you are using. The **inventory** file for the setup bundle installs and configures controller and private automation hub, including the credentials, and loading the initial execution environment images in both Private Automation Hub and Controller as well as the configuration.

It sounded like you didn't go through the setup in that method and you did several things manually. That means you need to setup Private Automation Hub with credentials, use Podman to load in initial execution environments, create credentials in automation controller, and setup automation controller to pull execution environment images from private automation hub.

Then you need to go to you job, organization, project and ensure you are setting one of the EEs that is setup on your private automation hub.

The initial installation would have setup and attempted to configure automation controller with the EEs from the private automation hub you deleted so you will need to most likely cleanup automation controller too so you only have true valid EEs for your environment.

**Comment by andysmagana** [comment]
Thanks. I just tried to modify my credential on AAP and instead of a
password I stuck the api token where a password or token go in credentials,
I put the username and the authentication url. I went back to the job
template ( just uses the command module to run uptime on a target)  this
time my error is:
Error: initializing source
docker://my.private.hub/ee-supported-rhel8:latest: Requesting bearer token:
Invalid status code from registry 403 ( forbidden )

**Comment by tmichett** [comment]
@andysmagana -

If you want general Ansible help or help with Controller or Private Automation hub, you can use the Red Hat Learning Community (RHLC). This would be a better place to get answers and assistance with general topics. I meant to put that on here where I closed the issue, but looks like I forgot.

https://learn.redhat.com/t5/Automation-Management-Ansible/bd-p/Automation
